# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: jenkins-new-monday12345-pv
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "D:/CICD/jenkins/jenkins-data" # Replace with your local path
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: jenkins-new-monday12345-pv-claim
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
# ---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
          - name: http-port
            containerPort: 8080
          - name: jnlp-port
            containerPort: 50000
      #   volumeMounts:
      #     - name: jenkins-vol
      #       mountPath: /var/jenkins_home
      # volumes:
      #   - name: jenkins-vol
      #     persistentVolumeClaim: 
      #       claimName: jenkins-new-monday12345-pv-claim
          
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: jenkins